# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el script de tiburón
COPY shark.py .

# Ejecutar el script
CMD ["python", "shark.py"]
